// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all

/**
 * SPDX-FileComment: Windows Security UI
 * SPDX-FileType: SOURCE
 * SPDX-FileContributor: ZHENG Robert
 * SPDX-FileCopyrightText: 2026 ZHENG Robert
 * SPDX-License-Identifier: Apache-2.0
 *
 * @file userconsentverifieravailability.go
 * @brief Windows Hello verifier availability enum (WinRT)
 * @version 1.0.0
 * @date 2026-06-02
 *
 * @author ZHENG Robert (robert@hase-zheng.net)
 * @copyright Copyright (c) 2026 ZHENG Robert
 * @LICENSE Apache-2.0
 */

package ui

// UserConsentVerifierAvailability indicates the availability of Windows Hello
// biometric verification on the current device, as defined by the WinRT API.
type UserConsentVerifierAvailability int32

// SignatureUserConsentVerifierAvailability is the WinRT type signature for the
// UserConsentVerifierAvailability enumeration.
const SignatureUserConsentVerifierAvailability string = "enum(Windows.Security.Credentials.UI.UserConsentVerifierAvailability;i4)"

// UserConsentVerifierAvailability values.
const (
	UserConsentVerifierAvailabilityAvailable            UserConsentVerifierAvailability = 0
	UserConsentVerifierAvailabilityDeviceNotPresent     UserConsentVerifierAvailability = 1
	UserConsentVerifierAvailabilityNotConfiguredForUser UserConsentVerifierAvailability = 2
	UserConsentVerifierAvailabilityDisabledByPolicy     UserConsentVerifierAvailability = 3
	UserConsentVerifierAvailabilityDeviceBusy           UserConsentVerifierAvailability = 4
	// UserConsentVerifierAvailabilityAvailable indicates Windows Hello is available.
	// UserConsentVerifierAvailabilityDeviceNotPresent indicates no biometric device is present.
	// UserConsentVerifierAvailabilityNotConfiguredForUser indicates the user has not configured Windows Hello.
	// UserConsentVerifierAvailabilityDisabledByPolicy indicates group policy disables Windows Hello.
	// UserConsentVerifierAvailabilityDeviceBusy indicates the biometric device is busy.
)
