// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all

/**
 * SPDX-FileComment: Windows Security UI
 * SPDX-FileType: SOURCE
 * SPDX-FileContributor: ZHENG Robert
 * SPDX-FileCopyrightText: 2026 ZHENG Robert
 * SPDX-License-Identifier: Apache-2.0
 *
 * @file userconsentverifier.go
 * @brief Windows Hello biometric verifier COM interop (WinRT)
 * @version 1.0.0
 * @date 2026-06-02
 *
 * @author ZHENG Robert (robert@hase-zheng.net)
 * @copyright Copyright (c) 2026 ZHENG Robert
 * @LICENSE Apache-2.0
 */

package ui

import (
	"syscall"
	"unsafe"

	"github.com/go-ole/go-ole"
	"github.com/saltosystems/winrt-go/windows/foundation"
)

// GUIDiUserConsentVerifierStatics is the COM GUID for the
// IUserConsentVerifierStatics WinRT activation factory.
const GUIDiUserConsentVerifierStatics string = "af4f3f91-564c-4ddc-b8b5-973447627c65"

// SignatureiUserConsentVerifierStatics is the WinRT type signature for the
// IUserConsentVerifierStatics activation factory.
const SignatureiUserConsentVerifierStatics string = "{af4f3f91-564c-4ddc-b8b5-973447627c65}"

// iUserConsentVerifierStatics wraps the IUserConsentVerifierStatics WinRT
// activation factory COM interface.
type iUserConsentVerifierStatics struct {
	ole.IInspectable
}

// iUserConsentVerifierStaticsVtbl is the COM vtable for the
// IUserConsentVerifierStatics interface, containing method slots for
// CheckAvailabilityAsync and RequestVerificationAsync.
type iUserConsentVerifierStaticsVtbl struct {
	ole.IInspectableVtbl

	UserConsentVerifierCheckAvailabilityAsync   uintptr
	UserConsentVerifierRequestVerificationAsync uintptr
}

// VTable returns the COM vtable pointer for the statics instance.
func (v *iUserConsentVerifierStatics) VTable() *iUserConsentVerifierStaticsVtbl {
	return (*iUserConsentVerifierStaticsVtbl)(unsafe.Pointer(v.RawVTable))
}

// UserConsentVerifierCheckAvailabilityAsync checks whether Windows Hello
// biometric verification is available on the current device. It returns an
// IAsyncOperation that yields a UserConsentVerifierAvailability value.
func UserConsentVerifierCheckAvailabilityAsync() (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Credentials.UI.UserConsentVerifier", ole.NewGUID(GUIDiUserConsentVerifierStatics))
	if err != nil {
		return nil, err
	}
	v := (*iUserConsentVerifierStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	hr, _, _ := syscall.SyscallN(
		v.VTable().UserConsentVerifierCheckAvailabilityAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}

// UserConsentVerifierRequestVerificationAsync prompts the user for Windows
// Hello biometric verification (fingerprint or face) with the given message.
// It returns an IAsyncOperation that yields a UserConsentVerificationResult.
func UserConsentVerifierRequestVerificationAsync(message string) (*foundation.IAsyncOperation, error) {
	inspectable, err := ole.RoGetActivationFactory("Windows.Security.Credentials.UI.UserConsentVerifier", ole.NewGUID(GUIDiUserConsentVerifierStatics))
	if err != nil {
		return nil, err
	}
	v := (*iUserConsentVerifierStatics)(unsafe.Pointer(inspectable))

	var out *foundation.IAsyncOperation
	messageHStr, err := ole.NewHString(message)
	if err != nil {
		return nil, err
	}
	hr, _, _ := syscall.SyscallN(
		v.VTable().UserConsentVerifierRequestVerificationAsync,
		uintptr(unsafe.Pointer(v)),    // this
		uintptr(messageHStr),          // in string
		uintptr(unsafe.Pointer(&out)), // out foundation.IAsyncOperation
	)

	if hr != 0 {
		return nil, ole.NewError(hr)
	}

	return out, nil
}
