// Code generated by winrt-go-gen. DO NOT EDIT.

//go:build windows

//nolint:all

/**
 * SPDX-FileComment: Windows Security UI
 * SPDX-FileType: SOURCE
 * SPDX-FileContributor: ZHENG Robert
 * SPDX-FileCopyrightText: 2026 ZHENG Robert
 * SPDX-License-Identifier: Apache-2.0
 *
 * @file userconsentverificationresult.go
 * @brief Windows Hello consent verification result enum (WinRT)
 * @version 1.0.0
 * @date 2026-06-02
 *
 * @author ZHENG Robert (robert@hase-zheng.net)
 * @copyright Copyright (c) 2026 ZHENG Robert
 * @LICENSE Apache-2.0
 */

package ui

// UserConsentVerificationResult represents the result of a Windows Hello
// user verification request, as defined by the WinRT API.
type UserConsentVerificationResult int32

// SignatureUserConsentVerificationResult is the WinRT type signature for the
// UserConsentVerificationResult enumeration.
const SignatureUserConsentVerificationResult string = "enum(Windows.Security.Credentials.UI.UserConsentVerificationResult;i4)"

// UserConsentVerificationResult values.
const (
	UserConsentVerificationResultVerified             UserConsentVerificationResult = 0
	UserConsentVerificationResultDeviceNotPresent     UserConsentVerificationResult = 1
	UserConsentVerificationResultNotConfiguredForUser UserConsentVerificationResult = 2
	UserConsentVerificationResultDisabledByPolicy     UserConsentVerificationResult = 3
	UserConsentVerificationResultDeviceBusy           UserConsentVerificationResult = 4
	UserConsentVerificationResultRetriesExhausted     UserConsentVerificationResult = 5
	UserConsentVerificationResultCanceled             UserConsentVerificationResult = 6
	// UserConsentVerificationResultVerified indicates the user successfully verified.
	// UserConsentVerificationResultDeviceNotPresent indicates no biometric device is available.
	// UserConsentVerificationResultNotConfiguredForUser indicates the user has not set up Windows Hello.
	// UserConsentVerificationResultDisabledByPolicy indicates group policy disables Windows Hello.
	// UserConsentVerificationResultDeviceBusy indicates the device is performing another operation.
	// UserConsentVerificationResultRetriesExhausted indicates the user exceeded the maximum retry count.
	// UserConsentVerificationResultCanceled indicates the user cancelled the verification dialog.
)
